spring:
  datasource:
    username: user
    password: user
    url: jdbc:mysql://localhost:3306/photo-gallery?serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  thymeleaf:
    cache: false
